# Generated by Django 4.2.2 on 2024-03-03 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_alter_customuser_photo_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='name',
            field=models.CharField(default='mironchikk', max_length=250, verbose_name='Имя'),
            preserve_default=False,
        ),
    ]
